# Generated by Django 3.2 on 2021-07-17 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=250, unique=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='other_names',
            field=models.CharField(max_length=250, unique=True, null=True),
            preserve_default=False,
        ),
    ]
